# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Env Secrets
    - shell: bash
      env:
        R25_USER: ${{ secrets.R25_USER }}
        R25_PASS: ${{ secrets.R25_PASS }}
        R25_BASEURL: ${{ secrets.R25_BASEURL }}
      run: |
        mkdir env-vars && cd env-vars && echo "{
          \"user\": \"$R25_USER\",
          \"password\": \"$R25_PASS\",
          \"baseUrl\": \"$R25_BASEURL\"
        }" >> r25ws.json
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
